### ISSUE TITLE
Open Loo Ahmedabad

### ISSUE THREAD

**Issue by jimishio** [DatameetAMD/open-ahmedabad-web#3]
Finding public washroom can be a troublesome to find for someone who doesn't belong to certain area or who is new to ahmedabad city and tranvellers!!

Government and Auda has created many open loo in each and every city area. 

SO from this web perspective, We will create a form where user can put information like below about public washroom : 

- latitude
- longitude
- address
- Paid or not
- Cleanliness (rating from 0 to 10)

This will help people to use public washrooms and city can be cleaned too.

**Comment by ndkcha** [comment]
Add "Open Hours" to the form.

**Comment by ndkcha** [comment]
Hosted on [github pages](https://datameetamd.github.io/open-loo/)!

**Comment by ndkcha** [comment]
The further discussions on this thread will be tracked here at DatameetAMD/bucket-list#2

**Comment by gnatih** [comment]
Now since there's quite some discussion about open-'data', what this repo contains is a tool to collect data. So maybe we need - 

1. To make the web-form available as a service - eg. hosted on github pages (thanks @ndkcha). So basically the html/js files reside only on the gh-pages branch.

2. Actually share the data ;) I guess the data currently gets submitted to Firebase. So we need another tool to bring that data back to this repo so that is available in an open way.

3. Guidelines for other users to actually use these tools, collect data and contribute.
